### import libraries

In [241]:
import numpy as np, time
import pandas as pd 
from faker import Faker as fk 
import matplotlib.pyplot as plt
fake = fk("fa_IR")
number_of_employees = 450 # without ceo

### Basic personal information

In [242]:
# national_code = 03 + 7/8 + 7 ranom number
d = pd.DataFrame({
    "n1": "03",
    "n2": np.random.choice([7, 8], size = number_of_employees).astype(str),
    "n3": np.random.randint(1000000, 10000000, size = number_of_employees).astype(str)
})

d["national_code"] = d["n1"] + d["n2"] + d["n3"]
d = d.drop(["n1", "n2", "n3"], axis=1)

# phone number = 09 + 9 random number
d["n1"] = "09"
d["n2"] = np.random.choice(["12", "19", "10"], size = number_of_employees)
d["n3"] = np.random.randint(1000000, 10000000, size = number_of_employees).astype(str)
d["phone_number"] = d["n1"] + d["n2"] + d["n3"]
d = d.drop(["n1", "n2", "n3"], axis=1)

# emergency contact   phone + name
d["n1"] = "09"
d["n2"] = np.random.choice(["12", "19", "10"], size = number_of_employees)
d["n3"] = np.random.randint(1000000, 10000000, size = number_of_employees).astype(str)
d_ecn = [{
    "emergency_contact_name": fake.name()
}
    for _ in range(number_of_employees)]
d["emergency_contact_phone"] = d["n1"] + d["n2"] + d["n3"]
d = d.drop(["n1", "n2", "n3"], axis=1)
    
d_1 = pd.DataFrame(d_ecn)
d = pd.concat([d, d_1], axis=1)

In [243]:
# first name
# last name
# father name
# gender
d_f = [{
    "first_name": fake.first_name_female(),
    "last_name": fake.last_name(),
    "gender": "خانم",
    "father_name": fake.first_name_male(),
    "email": fake.company_email()
}
    for _ in range(int(number_of_employees * 0.35))]
d_m = [{
    "first_name": fake.first_name_male(),
    "last_name": fake.last_name(),
    "gender": "آقا",
    "father_name": fake.first_name_male(),
    "email": fake.company_email()
}
    for _ in range(int(number_of_employees * 0.65))]
d_s = d_f + d_m
d_s = pd.DataFrame(d_s)
d = pd.concat([d, d_s], axis=1)

In [244]:
# # birth date
# dates = pd.date_range('1960-01-01', '2008-01-01', freq=' D')
# birth_date = np.random.choice(dates, size= number_of_employees, replace= True)
# d_s = pd.DataFrame(birth_date)
# d = pd.concat([d, d_s], axis=1)

# # marital status
# today = pd.Timestamp.today()
# marital_status = []
# for a in birth_date:
#     a = (today - a).days // 365
#     if a <= 22:
#         marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.95, 0.05]))
#     elif a <= 27:
#         marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.6, 0.4]))
#     elif a <= 35:
#         marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.3, 0.7]))
#     elif a <= 50:
#         marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.15, 0.85]))
#     else:
#         marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.1, 0.9]))
        
# marital_status = pd.DataFrame(marital_status)
# d["marital_status"] = marital_status
# d.rename(columns= { 0: "birth_date"}, inplace=True)

In [245]:
# address
d_s = [{
    "address": fake.street_address(),
}
    for _ in range(number_of_employees)]
d["address"] = pd.DataFrame(d_s)

In [246]:
# position
import pandas as pd
pos_num_emp = {
    # اداره امور حقوقی
    "مدیر ارشد حقوقی": 1,
    
    "مدیر دپارتمان دعاوی": 1,
    "مدیر دپارتمان شرکت ها": 1,
    "مدیر دپارتمان قراردداد ها": 1,
    "مدیر دپارتمان مالکیت فکری": 1,
    "مدیر دپارتمان تطبیق و انطباق": 1,
    "مدیر دپارتمان حقوق کار ": 1,
    "مدیر دپارتمان حقوق مالیاتی": 1,
    "مدیر دپارتمان تحقیقات حقوقی": 1,
    "مدیر دپارتمان مالی": 1,
    "مدیر دپارتمان منابع انسانی": 1,#10
    "مدیر دپارتمان فناوری اطلاعات": 1,
    "مدیر دپارتمان اداری": 1,
    "مدیر دپارتمان توسعه کسب و کار": 1,
    "مدیر دپارتمان حسابرسی داخلی": 1,
    
    # دعاوی
    "وکیل ارشد": 12,
    "وکیل": 32,
    "وکیل جوان": 20,# 5
    "دستیار حقوقی - دعاوی": 10,
    "کارشناسی پرونده": 11,
    
    # امور شرکتی
    "وکیل ارشد شرکتی": 6,
    "وکیل شرکتی": 15,
    "مشاور حقوقی - امور شرکتی ": 8,# 10
    "دستیار حقوقی - امور شرکتی": 5,
    
    # قرارداد ها
    "متخصص ارشد قرارداد ها": 5,
    "متخصص قرارداد ها": 14,
    "بازبین قرارداد ها": 8,
    "دستیار حقوقی - قرارداد ها": 5,# 15
    
    # مالکیت فکری
    "وکیل ثبت اختراع": 4,
    "وکیل علائم تجاری": 4,
    "متخصص مالکیت فکری": 6,
    "دستیار حقوقی - ماللکیت فکری": 4,
    
    # انطباق و تطبیق
    "افسر انطباق": 10,# 20
    "تحلیلگر ریسک": 6,
    "متخصص مقررات": 5,
    "حسابرس": 5,
    
    # کار و اشتغال
    "وکیل ارشد کار": 3,
    "وکیل کار": 8,# 25
    "مشاور حقوقی منابع انسانی": 4,
    "دستیار حقوقی - کار و اشتغال": 3,
    
    # مالیات
    "وکیل ارشد مالیاتی": 3,
    "وکیل مالیاتی": 7,
    "مشاور مالیاتی": 5,# 30
    "دستیار حقوقی - مالیات": 3,
    
    # پژوهش حقوقی
    "پژوهشگر ارشد حقوقی": 3,
    "پژوهشگر حقوقی": 8,
    "متخصص مستندسازی": 4,
    "کتابدار": 2,# 35
    
    # امور مالی
    "مدیر ارشد مالی": 1,
    "مدیر حسابداری": 1,
    "حسابدار ارشد": 4,
    "حسابدار": 10,
    "دستیار حسابداری": 4,#40
    "مدیر حقوق و دستمزد": 1,
    "متخصص حقوق و دستمزد": 4,
    "کارمند حقوق و دستمزد": 2,
    "مدیر برنامه ریزی مالی": 1,
    "تحلیلگر مالی": 7,#45
    "تحلیلگر بودجه": 5,
    
    # منابع انسانی
    "مدیر منابع انسانی": 1,
    "مدیر جذب و استخدام": 1,
    "کارشناس استخدام": 8,
    "متخصص جذب استعداد": 4,# 50
    "مدیر عملیات منابع انسانی": 1,
    "متخصص منابع انسانی": 8,
    "هماهنگ‌کننده منابع انسانی": 5,
    "مدیر آموزش": 1,
    "مربی": 4,# 55
    "متخصص یادگیری": 3,
    
    # فناوری اطلاعات
    "مدیر فناوری اطلاعات": 1,
    "مدیر زیرساخت": 1,
    "مدیر سیستم": 5,
    "مهندس شبکه": 4, # 60 
    "متخصص پشتیبانی فنی": 8,
    "مدیر نرم‌افزار": 1,
    "توسعه‌دهنده بک‌اند": 8,
    "توسعه‌دهنده فرانت‌اند": 5,
    "مهندس تضمین کیفیت": 5,  # 65
    "مدیر پایگاه داده": 2,
    "مدیر امنیت": 1,
    "تحلیلگر امنیت": 4,
    "متخصص مرکز عملیات امنیت": 3,
    
    # اداری
    "مدیر اداری": 1, # 70
    "مدیر دفتر": 2,
    "دستیار اجرایی": 5,
    "منشی": 6,
    "کارشناس تدارکات": 6,
    "کارمند اداری": 8, # 75
    
    # توسعه کسب و کار
    "مدیر توسعه کسب‌وکار": 1,
    "سرپرست توسعه کسب‌وکار": 2,
    "متخصص بازاریابی": 7,
    "متخصص فروش": 8,
    "متخصص مدیریت ارتباط با مشتری": 4,#80
    
    # حسابرسی داخلی
    "مدیر حسابرسی": 1,
    "حسابرس داخلی": 5,
    "حسابرس انطباق": 4,
    "افسر ریسک": 3,
}
pos = []
for position, count in pos_num_emp.items():
    pos.extend(np.full(count, position))

dep_num_emp = {
    "اداره امور حقوقی": 9,
    "دعاوی": 89,
    "امور شرکتی": 34,
    "قرارداد ها": 34,
    "مالکیت فکری": 18,
    "انطباق و تطبیق": 26,
    "کار و اشتغال": 18,
    "مالیات": 18,
    "پژوهش حقوقی": 17,
    "امور مالی": 40,
    "منابع انسانی": 36,
    "فناوری اطلاعات": 48,
    "اداری": 28,
    "توسعه کسب و کار": 22,
    "حسابرسی داخلی": 13,
}

dep = []
for department, count in dep_num_emp.items():
    dep.extend(np.full(count, department))
    
d_s = pd.DataFrame({"position": pos, "department": dep})
d =  pd.concat([d, d_s], axis=1)

In [247]:
# create ceo 
ceo_dic = {
    "national_code": "0362528876",
    "phone_number": "091277594481",
    "emergency_contact_phone": "09960857522",
    "emergency_contact_name": "منا محمدی",
    "first_name": "مریم",
    "last_name": "امینی خواه",
    "gender": "خانم",
    "father_name": "حسن",
    "email": "amaryam6674@gmail.com",
    # "birth_date": "1982-07-29 00:00:00",
    # "marital_status": "مجرد",
    "address": "80143 آوا کوچه واحد 560",
    "department": "مدیر عامل",
    "position": "مدیر عامل",
}
d = pd.concat([d, pd.DataFrame([ceo_dic])], ignore_index=True)

In [248]:
# field of study / education level
# based on position

fos_el_dic = {
    # اداره امور حقوقی
    "مدیر عامل": {"fos": {"حقوق": 0.3, "حقوق تجارت": 0.2, "مدیریت": 0.15, "مدیریت بازرگانی": 0.15, "MBA": 0.1, "مالی": 0.05, "اقتصاد": 0.05},
      "el": {"کارشناسی ارشد": 0.55,"دکتری": 0.2, "کارشناسی": 0.2, "پسادکتری": 0.05}},
    "مدیر ارشد حقوقی": {"fos": {"حقوق بین‌الملل": 0.2, "حقوق خصوصی": 0.2, "حقوق عمومی": 0.2, "حقوق کیفری": 0.2, "حقوق تجارت": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان دعاوی": {"fos": {"حقوق": 0.5, "حقوق بین‌الملل": 0.05, "حقوق خصوصی": 0.2, "حقوق قضایی": 0.1, "حقوق جزا و جرم شناسی": 0.15},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان شرکت ها": {"fos": {"حقوق": 0.5, "حقوق تجارت": 0.2, "حقوق شرکت ها": 0.2, "حقوق بازرگانی": 0.1},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان قراردداد ها": {"fos": {"حقوق": 0.4, "حقوق تجارت": 0.3, "حقوق قرارداد ها": 0.3},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان مالکیت فکری": {"fos": {"حقوق": 0.5, "حقوق مالکیت فکری": 0.5},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان تطبیق و انطباق": {"fos": {"حقوق": 0.5, "مدیریت": 0.2, "مالی": 0.15, "اقتصاد": 0.15},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان حقوق کار ": {"fos": {"حقوق": 0.5, "حقوق کار": 0.5},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان حقوق مالیاتی": {"fos": {"حقوق": 0.25, "حقوق مالیاتی": 0.25, "مالی": 0.25, "حسابداری": 0.25},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان تحقیقات حقوقی": {"fos": {"حقوق": 0.5, "مطالعات حقوقی": 0.5},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان مالی": {"fos": {"حقوق": 0.4, "حقوق مالیاتی": 0.3, "مالی": 0.3},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان منابع انسانی": {"fos": {"مدیریت منابع انسانی": 0.35, "اقتصاد": 0.3, "روان‌شناسی": 0.35},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان فناوری اطلاعات": {"fos": {"فناوری اطلاعات": 0.7, "مهندسی کامپیوتر": 0.3},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان اداری": {"fos": {"مدیریت دولتی": 0.5, "مدیریت بازرگانی": 0.5},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان توسعه کسب و کار": {"fos": {"بازاریابی": 0.5, "مدیریت بازرگانی": 0.5},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    "مدیر دپارتمان حسابرسی داخلی": {"fos": {"مدیریت ریسک": 0.25, "حسابداری": 0.25, "مالی": 0.25, "اقتصاد": 0.25},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.2, "کارشناسی": 0.1}},
    
    # دعاوی
    "وکیل ارشد": {"fos": {"حقوق": 0.5, "حقوق بین‌الملل": 0.05, "حقوق خصوصی": 0.2, "حقوق قضایی": 0.1, "حقوق جزا و جرم شناسی": 0.15},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "وکیل": {"fos": {"حقوق": 0.6, "حقوق خصوصی": 0.15, "حقوق بین‌الملل": 0.1, "حقوق عمومی": 0.05, "حقوق جزا و جرم شناسی": 0.1},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "وکیل جوان": {"fos": {"حقوق": 0.85, "حقوق خصوصی": 0.1, "حقوق جزا و جرم شناسی": 0.05},
      "el": {"کارشناسی ارشد": 0.15, "کارشناسی": 0.85}},
    "دستیار حقوقی - دعاوی": {"fos": {"حقوق": 0.7, "حقوق مطالعاتی": 0.3},
      "el": {"کارشناسی": 0.75, "کاردانی": 0.25}},
    "کارشناسی پرونده": {"fos": {"حقوق": 0.4, "حقوق مطالعاتی": 0.3, "مدیریت": 0.15, "مدیریت دولتی": 0.15},
      "el": {"کارشناسی ارشد": 0.15, "کارشناسی": 0.85}},
    
    # امور شرکتی
    "وکیل ارشد شرکتی": {"fos": {"حقوق": 0.3, "حقوق تجارت": 0.4, "حقوق شرکت ها": 0.2, "حقوق بازرگانی": 0.1},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "وکیل شرکتی": {"fos": {"حقوق": 0.4, "حقوق تجارت": 0.4, "حقوق شرکت ها": 0.2},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "مشاور حقوقی - امور شرکتی ": {"fos": {"حقوق": 0.5, "حقوق تجارت": 0.3, "حقوق بین‌الملل": 0.2},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "دستیار حقوقی - امور شرکتی": {"fos": {"حقوق": 0.7, "حقوق مطالعاتی": 0.3},
      "el": {"کارشناسی": 0.75, "کاردانی": 0.25}},
    
    # قرارداد ها
    "متخصص ارشد قرارداد ها": {"fos": {"حقوق": 0.2, "حقوق تجارت": 0.3, "حقوق قرارداد ها": 0.5},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "متخصص قرارداد ها": {"fos": {"حقوق": 0.2, "حقوق تجارت": 0.3, "حقوق قرارداد ها": 0.5},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "بازبین قرارداد ها": {"fos": {"حقوق": 0.6, "حقوق قرارداد ها": 0.4},
      "el": {"کارشناسی ارشد": 0.5, "کارشناسی": 0.5}},
    "دستیار حقوقی - قرارداد ها": {"fos": {"حقوق": 0.7, "حقوق مطالعاتی": 0.3},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    
    # مالکیت فکری
    "وکیل ثبت اختراع": {"fos": {"حقوق": 0.3, "حقوق مالکیت فکری": 0.5, "مهندسی کامپیوتر + حقوق": 0.1, "مهندسی برق + حقوق": 0.1},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "وکیل علائم تجاری": {"fos": {"حقوق": 0.5, "حقوق مالکیت فکری": 0.5},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "متخصص مالکیت فکری": {"fos": {"حقوق": 0.4, "حقوق مالکیت فکری": 0.6},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "دستیار حقوقی - ماللکیت فکری": {"fos": {"حقوق": 0.7, "حقوق مطالعاتی": 0.3},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    
    # انطباق و تطبیق
    "افسر انطباق": {"fos": {"حقوق": 0.4, "مدیریت بازرگانی": 0.25, "مالی": 0.2, "اقتصاد": 0.15},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "تحلیلگر ریسک": {"fos": {"مالی": 0.4, "اقتصاد": 0.3, "آمار": 0.2, "مدیریت ریسک": 0.1},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "متخصص مقررات": {"fos": {"حقوق": 0.6, "مدیریت دولتی": 0.25, "علوم سیاسی": 0.15},
      "el": {"کارشناسی ارشد": 0.5, "کارشناسی": 0.5}},
    "حسابرس": {"fos": {"حسابداری": 0.6, "مالی": 0.3, "اقتصاد": 0.1},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    
    # کار و اشتغال
    "وکیل ارشد کار": {"fos": {"حقوق": 0.5, "حقوق کار": 0.3, " حقوق خصوصی": 0.15, "حقوق عمومی": 0.05},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "وکیل کار": {"fos": {"حقوق": 0.6, "حقوق کار": 0.25, " حقوق خصوصی": 0.15},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "مشاور حقوقی منابع انسانی": {"fos": {"حقوق": 0.45, "حقوق کار": 0.3, "مدیریت منابع انسانی": 0.15, "مدیریت": 0.1},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "دستیار حقوقی - کار و اشتغال": {"fos": {"حقوق": 0.7, "حقوق مطالعاتی": 0.3},
      "el": {"کارشناسی": 0.75, "کاردانی": 0.25}},
    
    # مالیات
    "وکیل ارشد مالیاتی": {"fos": {"حقوق مالیاتی": 0.45, "حقوق": 0.3, "حسابداری": 0.15, "مالی": 0.1},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "وکیل مالیاتی": {"fos": {"حقوق مالیاتی": 0.45, "حقوق": 0.35, "مالی": 0.2},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "مشاور مالیاتی": {"fos": {"حسابداری": 0.4, "مالی": 0.35, "اقتصاد": 0.15, "حقوق مالیاتی": 0.1},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "دستیار حقوقی - مالیات": {"fos": {"حسابداری": 0.2, "حقوق": 0.6, "مطالعات حقوقی": 0.2},
      "el": {"کارشناسی": 0.75, "کاردانی": 0.25}},
    
    # پژوهش حقوقی
    "پژوهشگر ارشد حقوقی": {"fos": {"حقوق": 0.45, "مطالعات حقوقی": 0.3, "حقوق خصوصی": 0.15, "حقوق بین‌الملل": 0.1},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "پژوهشگر حقوقی": {"fos": {"حقوق": 0.6, "مطالعات حقوقی": 0.25, "حقوق خصوصی": 0.15},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "متخصص مستندسازی": {"fos": {"حقوق": 0.2, "مطالعات حقوقی": 0.2, "علم اطلاعات و دانش‌شناسی": 0.5 , "مدیریت اسناد": 0.1},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "کتابدار": {"fos": {"مطالعات حقوقی": 0.1, "علم اطلاعات و دانش‌شناسی": 0.7 , "مدیریت اسناد": 0.2},
      "el": {"کارشناسی": 0.75, "کاردانی": 0.25}},
    
    # امور مالی
    "مدیر ارشد مالی": {"fos": {"مالی": 0.5, "حسابداری": 0.3, "اقتصاد": 0.1, "MBA": 0.1},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "مدیر حسابداری": {"fos": {"مالی": 0.3, "حسابداری": 0.5, "اقتصاد": 0.2},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "حسابدار ارشد": {"fos": {"مالی": 0.3, "حسابداری": 0.5, "اقتصاد": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "حسابدار": {"fos": {"مالی": 0.5, "حسابداری": 0.3, "اقتصاد": 0.2},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "دستیار حسابداری": {"fos": {"مالی": 0.4, "حسابداری": 0.6},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "مدیر حقوق و دستمزد": {"fos": {"حسابداری": 0.4, "مدیریت منابع انسانی": 0.3, "مالی": 0.2, "مدیریت": 0.1},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "متخصص حقوق و دستمزد": {"fos": {"حسابداری": 0.5, "مدیریت منابع انسانی": 0.3, "مالی": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "کارمند حقوق و دستمزد": {"fos": {"حسابداری": 0.6, "مدیریت": 0.2, "مالی": 0.2},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "مدیر برنامه ریزی مالی": {"fos": {"حسابداری": 0.5, "اقتصاد": 0.3, "مالی": 0.1, "MBA": 0.1},
      "el": {"کارشناسی": 0.75, "کاردانی": 0.25}},
    "تحلیلگر مالی": {"fos": {"حسابداری": 0.3, "اقتصاد": 0.3, "مالی": 0.2, "آمار": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "تحلیلگر بودجه": {"fos": {"حسابداری": 0.3, "اقتصاد": 0.2, "مالی": 0.5},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    
    # منابع انسانی
    "مدیر منابع انسانی": {"fos": {"مدیریت": 0.3, "مدیریت منابع انسانی": 0.4, "روان‌شناسی": 0.2, "MBA": 0.1},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "مدیر جذب و استخدام": {"fos": {"مدیریت": 0.3, "مدیریت منابع انسانی": 0.5, "روان‌شناسی": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "کارشناس استخدام": {"fos": {"مدیریت": 0.3, "مدیریت منابع انسانی": 0.5, "روان‌شناسی": 0.2},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "متخصص جذب استعداد": {"fos": {"مدیریت": 0.3, "مدیریت منابع انسانی": 0.5, "روان‌شناسی": 0.2},
      "el": {"کارشناسی": 0.75, "کاردانی": 0.25}},
    "مدیر عملیات منابع انسانی": {"fos": {"مدیریت": 0.5, "مدیریت منابع انسانی": 0.3, "MBA": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "متخصص منابع انسانی": {"fos": {"مدیریت": 0.5, "مدیریت منابع انسانی": 0.3, "روان‌شناسی": 0.2},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "هماهنگ‌کننده منابع انسانی": {"fos": {"مدیریت": 0.3, "مدیریت منابع انسانی": 0.5, "روان‌شناسی": 0.2},
      "el": {"کارشناسی": 0.75, "کاردانی": 0.25}},
    "مدیر آموزش": {"fos": {"علوم تربیتی": 0.3, "مدیریت منابع انسانی": 0.4, "روان‌شناسی": 0.3},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "مربی": {"fos": {"علوم تربیتی": 0.5, "مدیریت منابع انسانی": 0.3, "روان‌شناسی": 0.2},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "متخصص یادگیری": {"fos": {"علوم تربیتی": 0.4, "مدیریت منابع انسانی": 0.3, "روان‌شناسی": 0.3},
      "el": {"کارشناسی": 0.75, "کاردانی": 0.25}},
    
    # فناوری اطلاعات
    "مدیر فناوری اطلاعات": {"fos": {"مهندسی کامپیوتر": 0.4, "علوم کامپیوتر": 0.3, "فناوری اطلاعات": 0.2, "MBA": 0.1},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "مدیر زیرساخت": {"fos": {"فناوری اطلاعات": 0.4, "مهندسی کامپیوتر": 0.3, "مهندسی شبکه": 0.3},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "مدیر سیستم": {"fos": {"فناوری اطلاعات": 0.7, "مهندسی کامپیوتر": 0.3},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "مهندس شبکه": {"fos": {"مهندسی کامپیوتر": 0.3, "مهندسی شبکه": 0.7},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "متخصص پشتیبانی فنی": {"fos": {"مهندسی کامپیوتر": 0.5, "علوم کامپیوتر": 0.3, "فناوری اطلاعات": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "مدیر نرم‌افزار": {"fos": {"مهندسی کامپیوتر": 0.3, "علوم کامپیوتر": 0.4, "مهندسی نرم‌افزار": 0.3},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "توسعه‌دهنده بک‌اند": {"fos": {"مهندسی کامپیوتر": 0.3, "علوم کامپیوتر": 0.3, "مهندسی نرم‌افزار": 0.4},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "توسعه‌دهنده فرانت‌اند": {"fos": {"فناوری اطلاعات": 0.3, "علوم کامپیوتر": 0.5, "مهندسی نرم‌افزار": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "مهندس تضمین کیفیت": {"fos": {"فناوری اطلاعات": 0.5, "علوم کامپیوتر": 0.3, "مهندسی نرم‌افزار": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "مدیر پایگاه داده": {"fos": {"مهندسی کامپیوتر": 0.3, "علوم کامپیوتر": 0.4, "فناوری اطلاعات": 0.3},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "مدیر امنیت": {"fos": {"امنیت سایبری": 0.5, "علوم کامپیوتر": 0.3, "فناوری اطلاعات": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "تحلیلگر امنیت": {"fos": {"امنیت سایبری": 0.5, "علوم کامپیوتر": 0.2, "فناوری اطلاعات": 0.3},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "متخصص مرکز عملیات امنیت": {"fos": {"امنیت سایبری": 0.6, "علوم کامپیوتر": 0.2, "فناوری اطلاعات": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    
    # اداری
    "مدیر اداری": {"fos": {"مدیریت": 0.5, "مدیریت دولتی": 0.3, "مدیریت بازرگانی": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "مدیر دفتر": {"fos": {"مدیریت": 0.5, "مدیریت دولتی": 0.3, "مدیریت بازرگانی": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "دستیار اجرایی": {"fos": {"مدیریت": 0.3, "زبان انگلیسی": 0.15, "مدیریت بازرگانی": 0.2, "روابط عمومی": 0.35},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "منشی": {"fos": {"مدیریت": 0.4, "روابط عمومی": 0.3, "امور دفتری": 0.3},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "کارشناس تدارکات": {"fos": {"مدیریت زنجیره تامین": 0.3, "مدیریت صنعتی": 0.3, "مدیریت بازرگانی": 0.4},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "کارمند اداری": {"fos": {"مدیریت": 0.4, "مدیریت دولتی": 0.3, "امور دفتری": 0.15, "حسابداری": 0.15},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    
    # توسعه کسب و کار
    "مدیر توسعه کسب‌وکار": {"fos": {"مدیریت بازرگانی": 0.4, "بازاریابی": 0.2, "اقتصاد": 0.1, "MBA": 0.3},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "سرپرست توسعه کسب‌وکار": {"fos": {"مدیریت بازرگانی": 0.5, "بازاریابی": 0.3, "اقتصاد": 0.2},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "متخصص بازاریابی": {"fos": {"مدیریت بازرگانی": 0.3, "بازاریابی": 0.5, "اقتصاد": 0.2},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "متخصص فروش": {"fos": {"مدیریت بازرگانی": 0.5, "بازاریابی": 0.3, "اقتصاد": 0.2},
      "el": {"کارشناسی": 0.75, "کاردانی": 0.25}},
    "متخصص مدیریت ارتباط با مشتری": {"fos": {"مدیریت بازرگانی": 0.4, "بازاریابی": 0.4, "فناوری اطلاعات": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    
    # حسابرسی داخلی
    "مدیر حسابرسی": {"fos": {"حسابداری": 0.5, "مالی": 0.3, "اقتصاد": 0.2},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
    "حسابرس داخلی": {"fos": {"حسابداری": 0.6, "مالی": 0.3, "اقتصاد": 0.1},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "حسابرس انطباق": {"fos": {"حسابداری": 0.4, "مالی": 0.3, "حقوق": 0.3},
      "el": {"کارشناسی ارشد": 0.35, "کارشناسی": 0.65}},
    "افسر ریسک": {"fos": {"مدیریت ریسک": 0.4, "مالی": 0.3, "اقتصاد": 0.2, "آمار": 0.1},
      "el": {"کارشناسی ارشد": 0.7, "دکتری": 0.25, "کارشناسی": 0.05}},
}
field_of_study = []
education_level = []

for position in d["position"]:

    fos_el = fos_el_dic[position]

    fos_choices = list(fos_el["fos"].keys())
    fos_probs = list(fos_el["fos"].values())
    el_choices = list(fos_el["el"].keys())
    el_probs = list(fos_el["el"].values())

    field_of_study.append(
        np.random.choice(fos_choices, p=fos_probs)
    )
    education_level.append(
        np.random.choice(el_choices, p=el_probs)
    )
        
d_s = pd.DataFrame({"field_of_study": field_of_study, "education_level": education_level})
d =  pd.concat([d, d_s], axis=1)
d

,national_code,phone_number,emergency_contact_phone,emergency_contact_name,first_name,last_name,gender,father_name,email,address,position,department,field_of_study,education_level
0,0375194143,09193350241,09123708786,محمد سعیدی,زینب,ملکیان,خانم,علي,izr@pdydh.ir,01975 مبین تونل سوئیت 349,مدیر ارشد حقوقی,اداره امور حقوقی,حقوق کیفری,دکتری
1,0387299847,09122717131,09194509405,مبين چنگیزی,حنانه,شبیری,خانم,آرش,myrrdkhbly@nyrw.com,403 رضا کوچه,مدیر دپارتمان دعاوی,اداره امور حقوقی,حقوق خصوصی,کارشناسی ارشد
2,0388128869,09191406973,09126647348,ایلیا تحسینی,نازنین,سغیری,خانم,متين,bsnyy@tyrjh.com,041 کابلی بلوار واحد 305,مدیر دپارتمان شرکت ها,اداره امور حقوقی,حقوق شرکت ها,کارشناسی ارشد
3,0373792266,09121840765,09129280843,علیرضا اشتری,سارا,ولاشجردی,خانم,محمدياسين,arsh49@mdny.ir,93410 مبینا جنب,مدیر دپارتمان قراردداد ها,اداره امور حقوقی,حقوق تجارت,کارشناسی ارشد
4,0375807310,09106858861,09192914483,جناب آقای یاسین سلطانی,مائده,جهانی,خانم,آرمين,mhdyszfry@srmyh.com,893 حریریان خیابان,مدیر دپارتمان مالکیت فکری,اداره امور حقوقی,حقوق مالکیت فکری,کارشناسی ارشد
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,0378427614,09128539010,09199921219,مهدیس همدانی,کيان,زنجانی,آقا,محمدجواد,mrymhmdny@bnkh.com,2821 ملکیان میدان,حسابرس انطباق,حسابرسی داخلی,مالی,کارشناسی ارشد
447,0376376633,09108095342,09121487821,بنيامين زمانی,یاسین,نعمتی,آقا,حسین,swgnd12@twlyd.com,879 صنایعی میدان واحد 387,افسر ریسک,حسابرسی داخلی,مالی,کارشناسی ارشد
448,0373992400,09108609814,09193899653,حدیث ربانی,محمدحسين,هومن,آقا,ايليا,ysyn62@frm.ir,5848 فاطمه میدان سوئیت 092,افسر ریسک,حسابرسی داخلی,مالی,کارشناسی
449,0385396024,09195481025,09122673608,سرکار خانم مهسا رسته,NaN,NaN,NaN,NaN,NaN,86560 حسین خیابان سوئیت 652,افسر ریسک,حسابرسی داخلی,مدیریت ریسک,دکتری
450,0362528876,091277594481,09960857522,منا محمدی,مریم,امینی خواه,خانم,حسن,amaryam6674@gmail.com,80143 آوا کوچه واحد 560,مدیر عامل,مدیر عامل,مدیریت بازرگانی,دکتری

In [249]:
# university
university = []
uni_list = ["دانشگاه تهران"," دانشگاه شهید بهشتی"," دانشگاه صنعتی شریف", "دانشگاه علامه طباطبایی",
            "دانشگاه تربیت مدرس", "دانشگاه علم و صنعت", "دانشگاه صنعتی امیرکبیر", "دانشگاه فردوسی مشهد",
            "George Washington University", "University of Texas at Austin", "University of Washington",
            "University of Florida", "Arizona State University", "University of Glasgow", "University of Leeds",
            "University of Nottingham", "University of California, Berkeley", "University of Pennsylvania",
            "Cornell University", "Duke University", "University of Michigan", "Northwestern University",
            "King's College London"]

for i in range(number_of_employees):
    university.append(np.random.choice(uni_list))
    
d_s = pd.DataFrame({"university": university})
d = pd.concat([d, d_s], axis=1)
d

,national_code,phone_number,emergency_contact_phone,emergency_contact_name,first_name,last_name,gender,father_name,email,address,position,department,field_of_study,education_level,university
0,0375194143,09193350241,09123708786,محمد سعیدی,زینب,ملکیان,خانم,علي,izr@pdydh.ir,01975 مبین تونل سوئیت 349,مدیر ارشد حقوقی,اداره امور حقوقی,حقوق کیفری,دکتری,University of Texas at Austin
1,0387299847,09122717131,09194509405,مبين چنگیزی,حنانه,شبیری,خانم,آرش,myrrdkhbly@nyrw.com,403 رضا کوچه,مدیر دپارتمان دعاوی,اداره امور حقوقی,حقوق خصوصی,کارشناسی ارشد,University of Nottingham
2,0388128869,09191406973,09126647348,ایلیا تحسینی,نازنین,سغیری,خانم,متين,bsnyy@tyrjh.com,041 کابلی بلوار واحد 305,مدیر دپارتمان شرکت ها,اداره امور حقوقی,حقوق شرکت ها,کارشناسی ارشد,دانشگاه علامه طباطبایی
3,0373792266,09121840765,09129280843,علیرضا اشتری,سارا,ولاشجردی,خانم,محمدياسين,arsh49@mdny.ir,93410 مبینا جنب,مدیر دپارتمان قراردداد ها,اداره امور حقوقی,حقوق تجارت,کارشناسی ارشد,University of Pennsylvania
4,0375807310,09106858861,09192914483,جناب آقای یاسین سلطانی,مائده,جهانی,خانم,آرمين,mhdyszfry@srmyh.com,893 حریریان خیابان,مدیر دپارتمان مالکیت فکری,اداره امور حقوقی,حقوق مالکیت فکری,کارشناسی ارشد,Cornell University
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,0378427614,09128539010,09199921219,مهدیس همدانی,کيان,زنجانی,آقا,محمدجواد,mrymhmdny@bnkh.com,2821 ملکیان میدان,حسابرس انطباق,حسابرسی داخلی,مالی,کارشناسی ارشد,University of Michigan
447,0376376633,09108095342,09121487821,بنيامين زمانی,یاسین,نعمتی,آقا,حسین,swgnd12@twlyd.com,879 صنایعی میدان واحد 387,افسر ریسک,حسابرسی داخلی,مالی,کارشناسی ارشد,Duke University
448,0373992400,09108609814,09193899653,حدیث ربانی,محمدحسين,هومن,آقا,ايليا,ysyn62@frm.ir,5848 فاطمه میدان سوئیت 092,افسر ریسک,حسابرسی داخلی,مالی,کارشناسی,دانشگاه علامه طباطبایی
449,0385396024,09195481025,09122673608,سرکار خانم مهسا رسته,NaN,NaN,NaN,NaN,NaN,86560 حسین خیابان سوئیت 652,افسر ریسک,حسابرسی داخلی,مدیریت ریسک,دکتری,Arizona State University
450,0362528876,091277594481,09960857522,منا محمدی,مریم,امینی خواه,خانم,حسن,amaryam6674@gmail.com,80143 آوا کوچه واحد 560,مدیر عامل,مدیر عامل,مدیریت بازرگانی,دکتری,NaN

In [ ]:
# # Job group
# job_group_kind = ["وکلا و مشاوران حقوقی", "پشتیبانی حقوقی", "ستادی", "مدیران"]
# d["job_group"] = np.random.choice(job_group_kind, size= number_of_employees, p= [0.45, 0.2, 0.2, 0.15])

In [253]:
# # hire date
# hire_date = []
# for i in range(len(d)):
#     if d["education_level"].iloc[i] == "دکتری":
#         min_year = pd.to_timedelta(9900, unit='D')
#     elif d["education_level"].iloc[i] == "کارشناسی ارشد":
#         min_year = pd.to_timedelta(8800, unit='D')
#     else:
#         min_year = pd.to_timedelta(8100, unit='D')
        
#     min_date = d["birth_date"].iloc[i] + min_year
    
#     end_date = pd.Timestamp('2026-01-01')
#     if min_date >= end_date:
#         min_date = end_date - pd.to_timedelta(365, unit='D')

#     hire_date_s = np.random.choice(pd.date_range(min_date, end_date, freq='D'))
#     hire_date.append(hire_date_s)

# d["hire_date"] = hire_date
# d["hire_date"].notna().count()

In [254]:
# # employment status 
# emplloyment_status_kind = ["فعال", "استعفا", "اخراج", "تعلیق"]
# employment_status = np.random.choice(emplloyment_status_kind, size=number_of_employees, p=[0.85, 0.07, 0.03, 0.05])
# d["employment_status"] = employment_status

In [255]:
# # employee id
# d["employee_id"] = "EMP" + (np.random.choice(np.arange(1000, 10000), size=number_of_employees, replace=False)).astype(str)

In [256]:
# d = d.sample(frac=1).reset_index(drop=True)

In [259]:
# # manager id found
# manager_positions = {
#     "مدیر IT", "مدیر مالی", "مدیر منابع انسانی", "مدیر اداری",
#     "مدیر پژوهش حقوقی", "مدیر واحد حقوقی", "مدیر ارشد عملیات",
#     "مدیر عملیات", "مدیر روابط عمومی", "معاون مدیریت",
#     "مشاور اسناد ارشد", "تحلیلگر قرارداد ارشد", "CEO", "وکیل متخصص"
# }

# mask = (d["employment_status"] == "فعال") & (d["position"].isin(manager_positions))
# manager_id_d = d[mask][["position", "department"]].copy()
# manager_id_d.index.name = "index"
# manager_id_d = manager_id_d.reset_index()

# manager_id_d

In [260]:
# # manager id assign
# hierarchy = {
#     # dept_name : (positions_of_employees_in_this_dept, positions_of_their_managers)
#     "فناوری اطلاعات":           (["کارشناس IT", "کارشناس IT ارشد"],
#                                 ["مدیر IT"]),
#     "مالی و حسابداری":          (["کارشناس مالی", "کارشناس مالی ارشد"],
#                                 ["مدیر مالی"]),
#     "منابع انسانی":             (["کارشناس منابع انسانی", "کارشناس منابع انسانی ارشد"],
#                                 ["مدیر منابع انسانی"]),
#     "اداری و پشتیبانی":         (["کارشناس اداری", "کارشناس اداری ارشد","کارشناس اداری حقوقی", "کارشناس روابط عمومی","کارشناس روابط عمومی ارشد"],
#                                 ["مدیر اداری"]),
#     "دپارتمان اسناد و مدارک":   (["کارشناس اسناد", "کارشناس اسناد ارشد"],
#                                 ["مشاور اسناد ارشد"]),
#     "دپارتمان تحقیقات حقوقی":   (["تحلیلگر حقوقی ارشد"],
#                                 ["مدیر پژوهش حقوقی"]),
#     "دپارتمان حقوقی قراردادها": (["وکیل پایه", "وکیل ارشد", "کارشناس قرارداد ارشد","مشاور حقوقی"],
#                                 ["تحلیلگر قرارداد ارشد"]),
#     "مشاوره حقوقی شرکتی":       (["وکیل پایه", "وکیل ارشد", "مشاور حقوقی","مشاور حقوقی ارشد"],
#                                 ["وکیل متخصص"]),
#     "مدیریت ارشد":              (["مدیر IT", "مدیر مالی", "مدیر منابع انسانی", "مدیر اداری","مشاور اسناد ارشد", "مدیر پژوهش حقوقی","تحلیلگر قرارداد ارشد", "وکیل متخصص","مدیر واحد حقوقی", "مدیر عملیات", "مدیر روابط عمومی"],
#                                 ["مدیر ارشد عملیات", "معاون مدیریت"]),
# }

# active = d["employment_status"] == "فعال"
# d["manager_id"] = pd.NA
# d["manager_id"] = d["manager_id"].astype("Int64")

# ceo_idx = d[d["position"] == "CEO"].index[0]

# for dept, (emp_pos, mgr_pos) in hierarchy.items():
#     mgr_idx = d[active & d["position"].isin(mgr_pos) & (d["department"] == dept)].index.tolist()
#     emp_idx = d[active & d["position"].isin(emp_pos) & (d["department"] == dept)
#                 & ~d.index.isin(mgr_idx)].index.tolist()

#     if not emp_idx:
#         continue
#     if not mgr_idx:
#         raise ValueError(f"'{dept}' کارمند دارد ولی مدیر فعال ندارد.")
#     if len(mgr_idx) > len(emp_idx):
#         raise ValueError(f"'{dept}': مدیران ({len(mgr_idx)}) از کارکنان ({len(emp_idx)}) بیشترند.")

#     for i, eidx in enumerate(emp_idx):
#         d.at[eidx, "manager_id"] = mgr_idx[i % len(mgr_idx)]

# senior_idx = d[active & d["position"].isin(["مدیر ارشد عملیات", "معاون مدیریت"])].index.tolist()
# for idx in senior_idx:
#     d.at[idx, "manager_id"] = ceo_idx

# d

In [261]:
# salary band

In [262]:
#  performance score

In [263]:
# leave day used(for every years they worked in this holding )

In [264]:
# برای کسایی که استعفا دادن تاریخ استعفا و علت استعفاشون

In [265]:
# d.info()